web:
  build: .
  ports:
    - "8880:8880"
  volumes:
    - ./part1/src:/part1/src
  links:
    - redis
  environment:
    - PORT_REDIS=6379
    - HOST_REDIS=redis

redis:
  image: redis
  volumes:
    - redis-data:/data
